# pretrained loading options
resume_train:
  load_dir: # pretrained model directory
  load_step: # pretrained model's step number

save_step: 10
model_dir: /tmp/mattport_models/

# dataset options
dataset:
  data_directory: data/lego
  dataset_type: blender
  downscale_factor: 1.0

# dataloader options
dataloader:
  num_workers: 0
  shuffle: true
  num_images_to_sample_from: 8
  num_rays_per_batch: 1024

# optimizer options
param_groups:
  graph:
    optimizer:
      type: Adam
      lr: 1e-4
    scheduler:
      type: StepLR
      step_size: 30
      gamma: 0.1
  camera:
    optimizer:
      type: SGD
      lr: 1e-4
    scheduler:
      type: ExponentialLR 
      gamma: 0.1


# machine options
machine_config:
  num_gpus: 4
  num_machines: 1
  machine_rank: 0
  dist_url: auto

# graph options
graph:
  # NOTE(ethan): currently setting to nothing b/c we're still designing the config format...
  _target_: mattport.nerf.graph.nerf.NeRFGraph