defaults:
  # This makes the logging module logs colorful
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    dir: outputs/${experiment_name}/${method_name}/${now:%Y-%m-%d_%H%M%S}

experiment_name: blender_lego
method_name: vanilla_nerf

# pretrained loading options
resume_train:
  load_dir: # pretrained model directory
  load_step: # pretrained model's step number

max_num_iterations: 1000000
steps_per_save: null
steps_per_log: 10
steps_per_test: 100

model_dir: /tmp/mattport_models/

# dataset options
dataset:
  data_directory: data/blender/lego
  dataset_type: blender
  downscale_factor: 4

# dataloader options
dataloader:
  num_workers: 0
  shuffle: true
  num_images_to_sample_from: 8
  num_rays_per_batch: 1024

# optimizer options
param_groups:
  fields:
    optimizer:
      type: Adam
      lr: 1e-4
    scheduler:
      type: StepLR
      step_size: 30 #  Period of learning rate decay.
      gamma: 0.1 # Multiplicative factor of learning rate decay. Default: 0.1.
  cameras:
    optimizer:
      type: SGD
      lr: 1e-4
    scheduler:
      type: ExponentialLR
      gamma: 0.1

# machine options
machine_config:
  num_gpus: 1
  num_machines: 1
  machine_rank: 0
  dist_url: auto

# graph options
graph:
  # NOTE(ethan): currently setting to nothing b/c we're still designing the config format...
  _target_: mattport.nerf.graph.vanilla_nerf.NeRFGraph
  near_plane: 1.0
  far_plane: 6.0
  num_coarse_samples: 64
  num_importance_samples: 64
