defaults:
  - default
  - override graph: instant_ngp_graph
  - _self_
method_name: instant_ngp
data.dataloader.num_rays_per_batch: 4096
data.val_num_rays_per_chunk: 16384
graph.network.field_implementation: tcnn