defaults:
  - vanilla_nerf
  - override data/dataset: friends_TBBT-big_living_room
  - _self_

experiment_name: friends_TBBT-big_living_room
method_name: semantic_nerf

graph:
  network:
    _target_: radiance.nerf.graph.semantic_nerf.SemanticNerfGraph
    near_plane: 0.1
    far_plane: 10.0
    num_coarse_samples: 64
    num_importance_samples: 64

    loss_coefficients: # loss coefficients
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
      semantic_loss_fine: 0.05