defaults:
  - default_graph.yaml
  - _self_

network:
  _target_: mattport.nerf.graph.instant_ngp.NGPGraph
  field_implementation: torch # torch, tcnn, ...
  loss_coefficients: # loss coefficients
    rgb_loss: 1.0

# optimizer options for network
param_groups:
  fields:
    optimizer:
      lr: 1e-2
