defaults:
  - default_graph.yaml
  - _self_

network:
  _target_: mattport.nerf.graph.instant_ngp.NGPGraph

# optimizer options for network
param_groups:
  fields:
    optimizer:
      type: Adam
      lr: 1e-2
