steps_per_log: 10
# stats tracker logs configurable training stats per iteration to terminal (e.g. rays/s, PSNR)
enable_stats: True
stats_tracker:
  max_history: 10
  stats_to_track: [ITER_LOAD_TIME, ITER_TRAIN_TIME] # see mattport/utils/stats_tracker.py for options
# writer logs losses and images per iteration
writer: 
  type: TensorboardWriter
  save_dir: './'
# profiler logs run times of functions and prints at end of training
enable_profiler: True