name: Check code for formating and run tests.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r environment/requirements.txt
        python setup.py develop
    - name: Run Black
      uses: psf/black@stable
      with:
        options: "--check --verbose --line-length=120"
    - name: Python Pylint
      run: |
        pylint mattport --max-line-length=120 --generated-members=numpy.*,torch.*,cv2.*,cv.* --good-names=e,c,i,j,x,y,lr,K,fx,fy,cx,cy,H,W --disable=too-many-arguments --disable=fixme
    - name: Test with pytest
      run: |
        pytest tests --ignore tests/nerf/test_ray_generator.py --typeguard-packages=mattport --torchtyping-patch-typeguard
